'use client';
import React, { useState } from 'react';

export default function LpNews() {
  const aprilFoolSummary = `April Fools' Day, celebrated annually on April 1st, is a day of lighthearted pranks, jokes, and hoaxes. While often seen as a day of harmless fun, it also presents a complex interplay of benefits and disadvantages. One of the primary benefits of April Fools' Day is its ability to foster a sense of community and shared laughter. Pranks, when executed well, can create memorable moments and strengthen bonds between friends, family, and colleagues. The anticipation of potential pranks can also inject a sense of excitement and playfulness into otherwise mundane routines. Moreover, April Fools' Day can serve as a creative outlet, encouraging individuals to think outside the box and develop clever pranks. This can stimulate ingenuity and problem-solving skills. However, April Fools' Day is not without its drawbacks. Pranks can sometimes cross the line from humorous to hurtful, causing emotional distress or even physical harm. Jokes that target sensitive issues, such as race, religion, or disability, are particularly problematic and can perpetuate harmful stereotypes. Furthermore, the spread of misinformation on April Fools' Day can have serious consequences. Fake news stories, even when intended as jokes, can cause confusion and panic, especially in today's climate of heightened anxiety. The potential for pranks to disrupt workplaces and educational institutions is another concern. Time wasted on planning and executing pranks can detract from productivity and learning. Additionally, the constant vigilance required to avoid being pranked can create a sense of unease and distrust. The ethical implications of April Fools' Day are also worth considering. While some view it as a harmless tradition, others argue that it encourages deception and dishonesty. The line between playful pranks and outright lies can be blurry, and some individuals may use April Fools' Day as an excuse to engage in manipulative behavior. Despite these potential drawbacks, April Fools' Day can be a valuable opportunity for self-reflection. It can prompt individuals to consider the impact of their words and actions on others, and to strive for humor that is both funny and compassionate. The key to a successful April Fools' Day lies in striking a balance between playful pranks and responsible behavior. By prioritizing respect, empathy, and good judgment, individuals can ensure that the day remains a source of joy and laughter for all. Ultimately, April Fools' Day is a complex and multifaceted tradition. While it offers opportunities for laughter, creativity, and community building, it also presents challenges related to ethics, safety, and misinformation. By approaching the day with mindfulness and consideration, individuals can maximize its benefits while minimizing its potential harms. The tradition continues to evolve, reflecting the changing social norms and values of each generation.`;

  const petrolPriceSummary = `The fluctuating prices of petrol have a profound impact on economies and individuals worldwide. These prices are influenced by a complex interplay of factors, including global supply and demand, geopolitical events, and currency exchange rates. When petrol prices rise, it leads to increased transportation costs for businesses and consumers alike. This ripple effect can trigger inflation, as the price of goods and services that rely on transportation also increases. For individuals, higher petrol prices can strain household budgets, forcing them to cut back on discretionary spending. This can have a negative impact on consumer confidence and overall economic growth. Governments often intervene in petrol markets to mitigate the effects of price volatility. They may use subsidies, taxes, or price controls to influence prices and protect consumers. However, these interventions can have unintended consequences, such as market distortions and reduced investment in alternative energy sources. The long-term trend in petrol prices is difficult to predict, as it depends on a variety of factors. The rise of electric vehicles and other alternative transportation technologies could reduce demand for petrol in the future. However, the pace of this transition is uncertain, and petrol is likely to remain a significant energy source for decades to come. The environmental impact of petrol consumption is another crucial consideration. The burning of fossil fuels contributes to climate change and air pollution, which have significant health and economic costs. Governments and businesses are increasingly focused on reducing their carbon footprint, but the transition to cleaner energy sources requires significant investment and policy changes. The geopolitical implications of petrol prices are also significant. Oil-producing nations hold considerable economic and political power, and fluctuations in petrol prices can have a major impact on their economies and foreign policies. This can lead to instability and conflict in some regions. The global economy is heavily reliant on petrol, and any disruption to its supply or pricing can have far-reaching consequences. This underscores the importance of diversifying energy sources and reducing dependence on fossil fuels. The search for sustainable and affordable energy solutions is a pressing challenge for governments and businesses worldwide. Innovations in renewable energy, energy storage, and transportation technologies are crucial for ensuring a stable and secure energy future. Ultimately, the prices of petrol remain a critical factor in the global economy and have far reaching consequences.`;

  const arsenalFulhamSummary = `The recent Arsenal vs. Fulham match was a highly anticipated clash between two London-based clubs, each with their own distinct styles and ambitions. Arsenal, known for their attacking prowess and possession-based football, entered the match as favorites, while Fulham, often regarded as underdogs, were determined to prove their mettle. The match began with Arsenal dominating possession, stringing together intricate passes and creating several scoring opportunities. Fulham, however, remained resolute in their defensive organization, frustrating Arsenal's attempts to break through their lines. As the first half progressed, Fulham gradually grew in confidence, launching counter-attacks and testing Arsenal's defense. The second half saw a more open and balanced contest, with both teams creating chances. Arsenal's attacking flair was evident, but Fulham's resilience and determination kept them in the game. The match was characterized by moments of individual brilliance, tactical battles, and dramatic twists. Arsenal's attacking players showcased their skill and creativity, while Fulham's defenders displayed their tenacity and discipline. The tactical approach of both managers was also a key factor in the match's outcome. Arsenal's possession-based style was contrasted by Fulham's more pragmatic approach, focusing on defensive solidity and counter-attacking threats. The match's intensity reached its peak in the closing stages, with both teams pushing for a decisive goal. Arsenal's persistence eventually paid off, as they found the net with a late strike, securing a hard-fought victory. Fulham, despite their valiant efforts, were left to rue their missed opportunities. The result of the match had significant implications for both teams' league positions. Arsenal's victory strengthened their pursuit of a top-four finish, while Fulham's defeat left them facing an uphill battle to avoid relegation. The match also provided valuable insights into the strengths and weaknesses of both teams. Arsenal's attacking prowess was evident, but their defensive vulnerabilities were exposed by Fulham's counter-attacks. Fulham's resilience and determination were commendable, but their lack of clinical finishing proved costly. The match served as a reminder of the unpredictable nature of football, where even the most dominant teams can be challenged by determined underdogs. The passion and intensity displayed by both teams showcased the unique character of London derbies, where local rivalries add an extra layer of significance to the contest.`;

  const nottmForestManUSummary = `The Nottingham Forest vs. Manchester United match was a highly anticipated encounter, pitting a newly promoted Forest side against the established giants of United. The match was expected to be a test of Forest's resilience and determination against United's superior quality and experience. The early stages of the match saw United asserting their dominance, controlling possession and creating scoring opportunities. Forest, however, remained organized and disciplined in their defensive shape, frustrating United's attempts to break through. As the first half progressed, Forest gradually grew in confidence, launching occasional counter-attacks and testing United's defense. The second half saw a more balanced contest, with both teams creating chances. United's attacking players showcased their individual brilliance, while Forest's defenders displayed their tenacity and commitment. The match was characterized by tactical battles, physical challenges, and moments of individual skill. United's possession-based style was contrasted by Forest's more direct approach, focusing on counter-attacks and set-piece opportunities. The match's intensity reached its peak in the closing stages, with both teams pushing for a decisive goal. United's persistence eventually paid off, as they found the net with a late strike, securing a narrow victory. Forest, despite their valiant efforts, were left to rue their missed opportunities and near misses. The result of the match had significant implications for both teams' league positions. United's victory strengthened their pursuit of a top-four finish, while Forest's defeat left them facing a tough battle to secure survival. The match also provided valuable insights into the strengths and weaknesses of both teams. United's attacking quality was evident, but their defensive vulnerabilities were exposed by Forest's counter-attacks. Forest's resilience and determination were commendable, but their lack of clinical finishing proved costly. The match served as a reminder of the unpredictable nature of football, where even the most dominant teams can be challenged by determined underdogs. The passion and intensity displayed by both teams showcased the unique character of Premier League football, where every match is a battle for points and survival.`;

  const aprilFoolJokesSummary = `April Fools' Day, celebrated annually on April 1st, is a day dedicated to lighthearted pranks, jokes, and hoaxes. The tradition, which has roots in various cultures, encourages individuals to engage in playful deception and trickery. The types of jokes and pranks employed on April Fools' Day vary widely, ranging from simple practical jokes to elaborate hoaxes. One common prank involves replacing sugar with salt or vice versa, leading to unexpected and humorous reactions. Fake news stories, often exaggerated or absurd, are also popular on April Fools' Day. These stories can range from announcements of bizarre scientific discoveries to reports of celebrity scandals. Technology has also played a significant role in the evolution of April Fools' Day pranks. Social media platforms and online forums provide fertile ground for spreading hoaxes and sharing humorous videos. The internet has also made it easier to coordinate elaborate pranks, involving multiple participants and complex setups. However, the rise of social media has also raised concerns about the spread of misinformation on April Fools' Day. Fake news stories, even when intended as jokes, can cause confusion and panic, especially in today's climate of heightened anxiety. The ethical implications of April Fools' Day are also worth considering. While some view it as a harmless tradition, others argue that it encourages deception and dishonesty. The line between playful pranks and outright lies can be blurry, and some individuals may use April Fools' Day as an excuse to engage in manipulative behavior. Despite these potential drawbacks, April Fools' Day can be a valuable opportunity for creativity and humor. It can prompt individuals to think outside the box and develop clever pranks, which can be a form of artistic expression. The day also serves as a reminder of the importance of laughter and playfulness in our lives. Humor can be a powerful tool for stress relief and social bonding. The key to a successful April Fools' Day lies in striking a balance between playful pranks and responsible behavior. By prioritizing respect, empathy, and good judgment, individuals can ensure that the day remains a source of joy and laughter for all. Ultimately, April Fools' Day is a complex and multifaceted tradition. While it offers opportunities for humor and creativity, it also presents challenges related to ethics, safety, and misinformation. By approaching the day with mindfulness and consideration, individuals can maximize its benefits while minimizing its potential harms.`;

  const coryBookerSummary = `Cory Booker, a prominent figure in American politics, has carved a reputation as a passionate advocate for social justice, economic equality, and criminal justice reform. His journey from a city councilman in Newark, New Jersey, to a United States Senator has been marked by a commitment to public service and a willingness to challenge the status quo. Booker's political philosophy is rooted in a belief in the power of community and the importance of addressing systemic inequalities. He has been a vocal critic of mass incarceration, advocating for sentencing reform and rehabilitation programs. His efforts to combat poverty and promote economic opportunity have also been a central focus of his career. Booker's ability to connect with people from diverse backgrounds has been a hallmark of his political style. He is known for his charismatic speaking style and his willingness to engage in open and honest dialogue. His use of social media has also allowed him to connect with a wider audience and build a strong online presence. Booker's political career has not been without its challenges. He has faced criticism from both the left and the right, and his policy positions have been subject to intense scrutiny. However, he has remained steadfast in his commitment to his core values and has continued to advocate for the issues he believes in. Booker's influence extends beyond the Senate floor. He is a sought-after speaker and commentator, and his views on social and political issues are widely respected. He has also been a strong advocate for bipartisanship, seeking common ground with colleagues from across the political spectrum. Booker's potential as a future leader in the Democratic Party has been a subject of much speculation. His ability to inspire and mobilize support has made him a prominent figure in national politics. His commitment to social justice and economic equality resonates with many Americans, particularly young people and those from marginalized communities. Booker's legacy is still being written, but his impact on American politics is undeniable. His dedication to public service and his unwavering commitment to his values have made him a force to be reckoned with. As he continues to advocate for change, his influence is likely to grow, shaping the future of American politics for generations to come.`;

  const sanDiegoBaseballSummary = `San Diego has a rich history of baseball, with the city playing a significant role in the development of the sport in Southern California. From its early days as a minor league town to its current status as a Major League Baseball city, San Diego has produced a wealth of talented players and memorable moments. One of the most iconic figures in San Diego baseball history is Tony Gwynn, a Hall of Fame outfielder who spent his entire 20-year career with the San Diego Padres. Gwynn's legendary hitting prowess and his commitment to the community made him a beloved figure in San Diego. The Padres, who joined the National League in 1969, have had their share of ups and downs. The team's first World Series appearance came in 1984, when they lost to the Detroit Tigers. The Padres returned to the World Series in 1998, but were swept by the New York Yankees. The team's current roster features a mix of veteran players and promising young talent. The Padres' farm system has also produced a number of highly regarded prospects, fueling hopes for a bright future. San Diego's baseball scene extends beyond the professional level. The city is home to a number of college and high school baseball programs, which have produced many talented players. The San Diego State Aztecs, for example, have a rich baseball tradition, producing players who have gone on to the Major Leagues. The city's passion for baseball is evident in the strong support for the Padres. Petco Park, the team's home stadium, is consistently ranked among the best ballparks in the country. The stadium's downtown location and its unique design have made it a popular destination for baseball fans. San Diego's baseball legacy is also intertwined with its military history. The city's large military population has contributed to the development of baseball in the region, with many players having served in the armed forces. The future of baseball in San Diego looks bright. The Padres' commitment to building a competitive team, coupled with the city's strong support for the sport, suggests that baseball will continue to thrive in San Diego for years to come. The city's rich baseball history and its passionate fan base make it a vital part of the American baseball landscape.`;

  const lsgVsPbksSummary = `The Lucknow Super Giants (LSG) vs. Punjab Kings (PBKS) match in the Indian Premier League (IPL) was a highly anticipated clash between two teams with contrasting styles and ambitions. LSG, a relatively new franchise, aimed to establish themselves as a dominant force in the league, while PBKS, a team with a rich history, sought to regain their past glory. The match began with both teams displaying their attacking intent, with batsmen from both sides showcasing their power-hitting abilities. LSG's batting lineup, known for its depth and firepower, aimed to set a challenging target for PBKS. PBKS, however, were determined to chase down the target, relying on their explosive top-order batsmen. The match was characterized by moments of individual brilliance, with both teams producing stunning performances with the bat and ball. LSG's bowlers, known for their variety and skill, aimed to restrict PBKS's scoring and take crucial wickets. PBKS's bowlers, however, were determined to disrupt LSG's batting rhythm and create opportunities for their team. The tactical battle between the two teams was also a key factor in the match's outcome. LSG's captaincy, known for its strategic acumen, aimed to outsmart PBKS's captaincy and guide their team to victory. PBKS's captaincy, however, aimed to employ innovative tactics and inspire their team to perform at their best. The match's intensity reached its peak in the closing stages, with both teams pushing for a decisive victory. LSG's fielding, known for its agility and athleticism, aimed to prevent PBKS from scoring crucial runs. PBKS's fielding, however, aimed to support their bowlers and create opportunities for run-outs and catches. The result of the match had significant implications for both teams' standings in the IPL points table. LSG's victory strengthened their position in the top half of the table, while PBKS's defeat left them facing an uphill battle to qualify for the playoffs. The match also provided valuable insights into the strengths and weaknesses of both teams. LSG's batting depth and bowling variety were evident, but their fielding lapses were a cause for concern. PBKS's batting explosiveness was commendable, but their bowling inconsistency proved costly. The match served as a reminder of the unpredictable nature of T20 cricket, where momentum can shift rapidly and anything can happen. The passion and intensity displayed by both teams showcased the unique character of the IPL, where every match is a battle for points and prestige.`;

  const maximeBouttierSummary = `Maxime Bouttier, a prominent figure in the Indonesian entertainment industry, has garnered widespread acclaim for his versatility as an actor and his captivating screen presence. His journey from a model to a celebrated actor has been marked by a dedication to his craft and a willingness to explore diverse roles. Bouttier's acting style is characterized by his ability to portray a wide range of emotions and characters. He has demonstrated his versatility in both dramatic and comedic roles, earning praise from critics and audiences alike. His ability to connect with viewers on an emotional level has made him a popular figure in Indonesian cinema and television. Bouttier's career has been marked by a series of successful projects, including films and television series that have resonated with audiences across Indonesia. His performances have often been praised for their authenticity and depth, showcasing his commitment to portraying characters with nuance and complexity. Bouttier's impact extends beyond his acting roles. He is also known for his philanthropic endeavors and his advocacy for various social causes. His involvement in charitable initiatives and his willingness to use his platform to raise awareness about important issues have earned him respect and admiration. Bouttier's popularity has also made him a sought-after brand ambassador and influencer. His ability to connect with a wide audience has made him an effective spokesperson for various products and causes. His influence on social media has also allowed him to engage with his fans and build a strong online presence. Bouttier's potential as a leading figure in Indonesian entertainment has been a subject of much speculation. His talent, charisma, and dedication to his craft have positioned him as a rising star in the industry. As he continues to explore new roles and challenge himself as an actor, his influence is likely to grow. Bouttier's journey is a testament to the power of hard work, dedication, and passion. His commitment to his craft and his willingness to use his platform for good have made him a role model for aspiring actors and fans alike. As he continues to evolve as an artist, his impact on the Indonesian entertainment industry is likely to be significant.`;

  const luigiMangioneSummary = `Luigi Mangione, a figure of interest in various circles, has been associated with a range of activities and pursuits. His background and experiences have contributed to a multifaceted persona, attracting attention from different sectors. Mangione's involvement in various projects and initiatives has often been characterized by a blend of innovation and pragmatism. His ability to navigate complex situations and find creative solutions has been noted by those who have worked with him. Mangione's approach to problem-solving often involves a combination of analytical thinking and practical application. He is known for his ability to identify key issues and develop effective strategies for addressing them. His communication skills and his ability to build relationships have also been cited as strengths. Mangione's network of contacts and his ability to connect with people from diverse backgrounds have been valuable assets in his various endeavors. His knowledge and expertise in certain areas have made him a sought-after advisor and consultant. His insights and perspectives have been valued by those seeking guidance on complex matters. Mangione's impact has been felt in various sectors, ranging from business and technology to social and cultural initiatives. His ability to bridge different disciplines and bring together diverse perspectives has been a hallmark of his work. Mangione's contributions have often been characterized by a commitment to innovation and a desire to make a positive impact. His efforts to promote new ideas and solutions have been recognized by those who have benefited from his work. Mangione's legacy is still being written, but his influence has been felt in various ways. His ability to connect with people, his strategic thinking, and his commitment to innovation have made him a figure of note. As he continues to pursue his various interests and endeavors, his impact is likely to grow.`;

  const nicoletteBoeleSummary = `Nicolette Boele, a figure known for her expertise in sustainable finance and responsible investment, has made significant contributions to the field. Her work focuses on integrating environmental, social, and governance (ESG) factors into investment decisions, aiming to promote long-term value creation and positive societal impact. Boele's career has been marked by her dedication to advocating for transparency and accountability in corporate practices. She has been instrumental in developing frameworks and guidelines for ESG reporting, enabling investors to make informed decisions based on comprehensive data. Her expertise extends to analyzing the financial risks and opportunities associated with climate change, social inequality, and corporate governance. She has played a crucial role in raising awareness about the importance of considering these factors in investment strategies. Boele's influence extends beyond the financial sector. She has been actively involved in policy discussions and initiatives aimed at promoting sustainable development. Her insights and recommendations have been valued by governments, international organizations, and civil society groups. Her commitment to fostering collaboration and knowledge sharing has led to the establishment of platforms and networks for sustainable finance professionals. She has been instrumental in building capacity and promoting best practices in the field. Boele's research and publications have contributed to the growing body of knowledge on sustainable finance. Her work has been cited by academics, practitioners, and policymakers, shaping the discourse on responsible investment. Her ability to communicate complex concepts in a clear and accessible manner has made her a sought-after speaker and commentator. She has been invited to present at conferences, workshops, and seminars around the world. Boele's leadership in the field has been recognized through various awards and accolades. Her dedication to promoting sustainable finance and her commitment to ethical principles have earned her respect and admiration. Her work serves as an inspiration for aspiring professionals and demonstrates the potential for finance to drive positive social and environmental change. Her contributions have helped to shape the evolving landscape of responsible investment, paving the way for a more sustainable and equitable future.`;

  const rbaInterestRatesSummary = `The Reserve Bank of Australia's (RBA) interest rate decisions have a profound impact on the Australian economy. These decisions are carefully considered, taking into account a wide range of economic indicators and forecasts. The RBA's primary objective is to maintain price stability, which means keeping inflation within a target range. To achieve this, the RBA adjusts the cash rate, which influences borrowing costs for businesses and consumers. When inflation is high, the RBA may raise interest rates to cool down the economy and prevent prices from spiraling out of control. Conversely, when the economy is weak, the RBA may lower interest rates to stimulate growth and encourage spending. The RBA's decisions are not made in isolation. They are influenced by global economic conditions, such as the performance of major trading partners and the stability of international financial markets. The RBA also closely monitors domestic factors, such as employment levels, consumer spending, and business investment. The RBA's communication strategy is crucial in managing expectations and providing clarity to the public. The RBA releases statements explaining its decisions and provides forecasts for the economy. The RBA also engages in public speaking and releases publications to educate the public about monetary policy. The impact of RBA interest rate decisions extends beyond the financial sector. Changes in borrowing costs affect housing markets, business investment, and consumer confidence. The RBA's decisions can also influence the exchange rate, which has implications for trade and tourism. The RBA's role in the Australian economy is significant, and its decisions are closely watched by businesses, investors, and consumers. The RBA's independence and its commitment to transparency and accountability are essential for maintaining public trust in the central bank. The RBA's ability to navigate economic challenges and maintain price stability is crucial for the long-term prosperity of Australia. The RBA's policies play a vital role in shaping the economic landscape and influencing the lives of Australians.`;

  const tomHollandSpiderManSummary = `Tom Holland's portrayal of Spider-Man in the Marvel Cinematic Universe (MCU) has captivated audiences worldwide. His fresh take on the iconic superhero has brought a new level of relatability and youthful energy to the character. Holland's performance is characterized by his ability to balance the humor and awkwardness of a teenage Peter Parker with the heroism and responsibility of Spider-Man. He has seamlessly integrated the character into the MCU, building strong relationships with other superheroes and contributing to the overall narrative. Holland's dedication to the role is evident in his physical preparation and his commitment to performing his own stunts. He has trained extensively in parkour and gymnastics, allowing him to deliver action sequences with authenticity and dynamism. His chemistry with his co-stars, particularly Zendaya and Jacob Batalon, has been a highlight of the Spider-Man films. Their on-screen friendship feels genuine and adds a layer of heart to the action-packed storylines. Holland's portrayal has resonated with a new generation of Spider-Man fans, while also appealing to long-time enthusiasts of the character. His ability to capture the essence of Peter Parker's struggles and triumphs has made him a beloved figure in popular culture. Holland's impact extends beyond the Spider-Man films. He has also appeared in other MCU movies, contributing to the interconnected narrative of the franchise. His performances have been praised for their emotional depth and their ability to connect with audiences on a personal level. Holland's future in the MCU remains a topic of much speculation. Fans are eager to see how his character will evolve and what challenges he will face in future installments. His portrayal of Spider-Man has cemented his status as a rising star in Hollywood, and his career is poised for continued success.`;

  const lakersRocketsSummary = `A Lakers vs. Rockets game is a highly anticipated matchup, featuring two teams with distinct styles and ambitions. The Lakers, known for their star-studded roster and championship pedigree, aim to dominate the Western Conference. The Rockets, often characterized by their fast-paced, high-scoring offense, seek to disrupt the established order. The game typically showcases a clash of contrasting strategies. The Lakers often rely on their experienced veterans and their ability to control the tempo of the game. The Rockets, in contrast, prefer to push the pace and generate scoring opportunities through fast breaks and three-point shooting. The individual matchups between key players are always a highlight of the game. The Lakers' star players often face off against the Rockets' dynamic scorers, creating exciting moments of skill and athleticism. The game's intensity is often heightened by the rivalry between the two teams. Their past encounters and their contrasting styles create a sense of anticipation and excitement. The outcome of a Lakers vs. Rockets game can have significant implications for both teams' playoff aspirations. A victory can boost morale and solidify their position in the standings. A loss can create doubt and put pressure on their future performance. The game also provides valuable insights into the strengths and weaknesses of both teams. The Lakers' ability to execute their game plan and control the boards is often tested by the Rockets' offensive firepower. The Rockets' defensive resilience is often challenged by the Lakers' experienced scorers. The game serves as a reminder of the unpredictable nature of basketball, where momentum can shift rapidly and anything can happen. The passion and intensity displayed by both teams showcase the competitive spirit of the NBA, where every game is a battle for victory.`;

  const rexHeuermannSummary = `Rex Heuermann's case has garnered significant attention due to the serious nature of the allegations against him. The details surrounding his arrest and the subsequent investigation have raised numerous questions and sparked widespread public interest. The allegations against Heuermann involve serious criminal charges, and the legal proceedings are expected to be complex and lengthy. The investigation has involved extensive forensic analysis and the examination of various pieces of evidence. The media coverage of the case has been extensive, with numerous news outlets providing updates on the investigation and the legal proceedings. The public's reaction to the case has been one of shock and disbelief, given the nature of the allegations. The legal implications of the case are significant, and the outcome will have far-reaching consequences. The case has also raised questions about law enforcement procedures and the effectiveness of investigative techniques. The community where Heuermann resided has been deeply affected by the allegations, and the case has created a sense of unease and concern. The legal team representing Heuermann is expected to mount a vigorous defense, and the trial will be closely watched by legal experts. The case serves as a reminder of the importance of due process and the presumption of innocence until proven guilty. The legal proceedings are expected to be lengthy and complex, and the outcome will have significant implications for all parties involved. The case has also highlighted the importance of addressing issues related to criminal behavior and ensuring public safety.`;

  const spiderManBrandNewDaySummary = `Spider-Man: Brand New Day was a significant storyline in the Spider-Man comic book series, marking a major shift in the character's status quo. The story arc followed the controversial "One More Day" storyline, which erased Peter Parker's marriage to Mary Jane Watson. Brand New Day aimed to revitalize the Spider-Man comics, introducing new characters, villains, and storylines. The storyline focused on Peter Parker's attempts to rebuild his life after the events of "One More Day." He faced new challenges, including financial struggles, relationship issues, and the emergence of new threats. The Brand New Day era introduced several new supporting characters, such as Carlie Cooper, Vin Gonzales, and Jackpot. These characters added new dynamics to Peter Parker's life and created fresh storylines. The storyline also featured the return of classic Spider-Man villains, such as Mister Negative and Freak. These villains were reimagined for the Brand New Day era, presenting new challenges for Spider-Man. The Brand New Day storyline was met with mixed reviews from fans. Some praised the fresh direction and the introduction of new characters, while others criticized the erasure of Peter Parker's marriage. The storyline's impact on the Spider-Man comics was significant, shaping the character's direction for several years. Brand New Day also explored themes of responsibility, redemption, and the consequences of one's actions. These themes are central to the Spider-Man mythos and resonated with readers. The storyline's legacy continues to be debated among Spider-Man fans, with its impact on the character's history remaining a topic of discussion. Brand New Day represents a pivotal moment in Spider-Man's history, marking a period of change and renewal for the iconic superhero.`;

  const buyCanadianMovementSummary = `The "Buy Canadian" movement is a campaign that encourages consumers to purchase goods and services produced in Canada. The movement aims to support Canadian businesses, create jobs, and stimulate the domestic economy. Advocates of the movement argue that buying Canadian products helps to strengthen local communities and reduce reliance on foreign imports. They also emphasize the importance of supporting Canadian workers and ensuring fair labor practices. The movement has gained momentum in recent years, as concerns about globalization and the impact of foreign competition have grown. Supporters of the movement often highlight the quality and safety of Canadian-made products. They argue that Canadian businesses adhere to high standards of production and environmental sustainability. The "Buy Canadian" movement also promotes a sense of national pride and identity. It encourages Canadians to support their own industries and contribute to the country's economic prosperity. Critics of the movement argue that it can lead to higher prices for consumers and limit their choices. They also argue that it can create trade barriers and harm international relations. The impact of the "Buy Canadian" movement on the Canadian economy is a subject of debate. Some studies suggest that it can have a positive effect on job creation and economic growth. Other studies suggest that its impact is limited and that it can have unintended consequences. The movement's success depends on various factors, including consumer awareness, government policies, and the competitiveness of Canadian businesses. The "Buy Canadian" movement reflects a growing trend towards localism and a desire to support domestic industries. It highlights the importance of balancing global trade with the need to protect local economies.`;

  const hootersSummary = `Hooters is a well-known restaurant chain that has garnered attention for its unique brand and marketing strategy. The establishment is known for its casual dining atmosphere, its signature chicken wings, and its distinctive waitstaff. The Hooters brand has become synonymous with a particular image, which has both attracted and repelled customers. The company's marketing strategy has often been the subject of controversy, with some critics arguing that it objectifies women. Hooters has defended its business model, arguing that it provides a fun and entertaining dining experience. The restaurant chain has expanded its menu over the years, offering a variety of food and beverage options. However, its signature chicken wings remain its most popular item. Hooters has also expanded its reach beyond the United States, with locations in various countries around the world. The company's success can be attributed to its ability to create a distinctive brand and cater to a specific target audience. Hooters has also faced challenges related to changing social norms and increased scrutiny of its business practices. The company has attempted to adapt its image and marketing strategy in response to these challenges. The Hooters brand remains a topic of discussion, with its unique identity continuing to generate both praise and criticism. The company's ability to navigate these challenges will determine its future success and relevance.`;

  const warrenBuffettSummary = `Warren Buffett is one of the most successful investors in history, known for his value investing philosophy and his long-term approach to the stock market. His company, Berkshire Hathaway, has generated exceptional returns for its shareholders over the decades. Buffett's investment strategy focuses on buying undervalued companies with strong management and sustainable competitive advantages. He emphasizes the importance of understanding a company's business model and its long-term prospects. Buffett is also known for his conservative approach to investing, avoiding complex financial instruments and focusing on companies with simple and predictable businesses. His investment decisions are guided by his principles of value, patience, and discipline. Buffett's wisdom and insights have made him a respected figure in the financial world. He is often quoted for his advice on investing and business. Buffett's philanthropic endeavors have also garnered attention. He has pledged to donate the vast majority of his wealth to charitable causes, primarily through the Bill & Melinda Gates Foundation. Buffett's influence extends beyond the financial world. He is also known for his down-to-earth personality and his ability to communicate complex concepts in a clear and accessible manner. His annual letters to Berkshire Hathaway shareholders are widely read and analyzed by investors. Buffett's legacy as an investor and philanthropist is secure. His principles and insights have shaped the way many people think about investing and business.`;

  const elSalvadorSummary = `El Salvador, a Central American nation, has a rich history and a complex social and political landscape. The country has faced numerous challenges, including civil war, natural disasters, and economic inequality. El Salvador's history is marked by periods of political instability and social unrest. The country's civil war, which lasted from 1980 to 1992, had a profound impact on its society and economy. El Salvador's economy is heavily reliant on remittances from Salvadorans living abroad. The country has also faced challenges related to poverty, crime, and gang violence. The government of El Salvador has implemented various policies aimed at addressing these challenges, but progress has been slow. El Salvador's natural beauty and cultural heritage have made it a popular destination for tourists. The country's beaches, volcanoes, and Mayan ruins attract visitors from around the world. El Salvador's efforts to promote tourism have been hampered by concerns about safety and security. The country's relationship with the United States has been a significant factor in its political and economic development. El Salvador has received significant aid from the United States, but this relationship has also been marked by periods of tension. El Salvador's efforts to diversify its economy and attract foreign investment have been ongoing. The country has sought to improve its infrastructure and create a more business-friendly environment. El Salvador's social and political landscape continues to evolve, and the country faces numerous challenges as it seeks to build a more prosperous and equitable future.`;

  const initialNews = [
    {
      category: 'General',
      title: 'April Fools\' Day Benefits and Disadvantages',
      content: aprilFoolSummary,
    },
    {
      category: 'Economy',
      title: 'Petrol Price Summary',
      content: petrolPriceSummary,
    },
    {
      category: 'Sports',
      title: 'Arsenal vs. Fulham Match Summary',
      content: arsenalFulhamSummary,
    },
    {
      category: 'Sports',
      title: 'Nottingham Forest vs. Manchester United Match Summary',
      content: nottmForestManUSummary,
    },
    {
      category: 'Humor',
      title: 'April Fools\' Day Jokes and Pranks Summary',
      content: aprilFoolJokesSummary,
    },
    {
      category: 'Politics',
      title: 'Cory Booker Summary',
      content: coryBookerSummary,
    },
    {
      category: 'Sports',
      title: 'San Diego Baseball Summary',
      content: sanDiegoBaseballSummary,
    },
    {
      category: 'Sports',
      title: 'LSG vs PBKS IPL Match Summary',
      content: lsgVsPbksSummary,
    },
    {
      category: 'Entertainment',
      title: 'Maxime Bouttier Summary',
      content: maximeBouttierSummary,
    },
    {
      category: 'General',
      title: 'Luigi Mangione Summary',
      content: luigiMangioneSummary,
    },
    { category: 'Finance', title: 'Nicolette Boele Summary', content: nicoletteBoeleSummary },
    { category: 'Finance', title: 'RBA Interest Rates Australia Summary', content: rbaInterestRatesSummary },
    { category: 'Entertainment', title: 'Tom Holland Spider-Man Summary', content: tomHollandSpiderManSummary },
    { category: 'Sports', title: 'Lakers vs. Rockets Summary', content: lakersRocketsSummary },
    { category: 'News', title: 'Rex Heuermann Summary', content: rexHeuermannSummary },
    { category: 'Entertainment', title: 'Spider-Man Brand New Day Summary', content: spiderManBrandNewDaySummary },
    { category: 'Economy', title: 'Buy Canadian Movement Summary', content: buyCanadianMovementSummary },
    { category: 'Business', title: 'Hooters Summary', content: hootersSummary },
    { category: 'Finance', title: 'Warren Buffett Summary', content: warrenBuffettSummary },
    { category: 'World', title: 'El Salvador Summary', content: elSalvadorSummary },

  ];

  const [news, setNews] = useState(initialNews);
  const [expandedNews, setExpandedNews] = useState({});

  const getNewsByCategory = (category) => {
    return initialNews.filter((item) => item.category === category);
  };

  const toggleExpand = (index) => {
    setExpandedNews((prevExpanded) => ({
      ...prevExpanded,
      [index]: !prevExpanded[index],
    }));
  };

  const truncateContent = (content, index) => {
    if (content.length > 70) {
      const truncated = content.substring(0, 70);
      const remaining = content.substring(70);
      return (
        <>
          {truncated}
          {expandedNews[index] && <>{remaining}</>}
          <button
            onClick={() => toggleExpand(index)}
            className="text-blue-400 mt-2"
          >
            {expandedNews[index] ? 'Show Less' : 'Show More'}
          </button>
        </>
      );
    }
    return content;
  };

  return (
    <div className="bg-gradient-to-r from-blue-900 via-purple-800 to-indigo-900 min-h-screen text-white p-6">
      <div className="max-w-5xl mx-auto">
        <h2 className="text-center font-extrabold text-4xl mb-4">Daily News</h2>
        <hr className="border-gray-400 my-4" />

        <div className="flex justify-around mb-6">
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(initialNews)}
          >
            All News
          </button>
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(getNewsByCategory('General'))}
          >
            General
          </button>
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(getNewsByCategory('Economy'))}
          >
            Economy
          </button>
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(getNewsByCategory('Sports'))}
          >
            Sports
          </button>
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(getNewsByCategory('Humor'))}
          >
            Humor
          </button>
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(getNewsByCategory('Politics'))}
          >
            Politics
          </button>
          <button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => setNews(getNewsByCategory('Entertainment'))}
          >
            Entertainment
          </button>
        </div>

        {news.map((item, index) => (
          <div key={index} className="bg-gray-800 rounded-lg p-4 mb-4 shadow-lg">
            <h3 className="font-bold text-xl mb-2">{item.title}</h3>
            <p>{truncateContent(item.content, index)}</p>
            <p className="text-gray-400 mt-2">Category: {item.category}</p>
          </div>
        ))}
      </div>
    </div>
  );
}










