'use client';
import React from 'react';

const jobSummaries = {
  frontend: `Landing a frontend developer job in today's competitive tech landscape requires a blend of technical prowess, a compelling portfolio, and effective networking. Frontend development focuses on building the user interface (UI) and user experience (UX) of websites and web applications, making it a crucial role in creating engaging and accessible digital experiences. To stand out, aspiring frontend developers should master core technologies such as HTML, CSS, and JavaScript. A deep understanding of these languages, along with proficiency in modern frameworks and libraries like React, Angular, or Vue.js, is essential. Employers often look for candidates who can demonstrate their ability to build responsive and performant web applications. Building a strong portfolio is paramount. Showcase your projects, highlighting your technical skills and design sensibilities. Include projects that demonstrate your ability to work with APIs, manage state, and implement complex UI components. Contribution to open-source projects or personal projects that solve real-world problems can significantly boost your credibility. Networking plays a vital role in landing a frontend job. Attend industry events, join online communities, and connect with professionals on platforms like LinkedIn. Building relationships with recruiters and hiring managers can open doors to opportunities that might not be publicly advertised. Soft skills are equally important. Communication, teamwork, and problem-solving skills are highly valued in collaborative development environments. Be prepared to discuss your approach to problem-solving, your ability to work in a team, and your communication style during interviews. Continuous learning is essential in the ever-evolving world of frontend development. Stay updated with the latest trends, tools, and best practices. Follow industry blogs, attend webinars, and take online courses to enhance your skills. Certifications from reputable organizations can also validate your knowledge and expertise. Tailor your resume and cover letter to each job application, highlighting the skills and experiences that align with the job requirements. Use keywords from the job description to ensure your application gets noticed by applicant tracking systems (ATS). Prepare for technical interviews by practicing coding challenges and reviewing fundamental concepts. Be ready to discuss your projects in detail, explaining your design decisions and technical implementations. A positive attitude, a willingness to learn, and a passion for frontend development are crucial for success. Demonstrate your enthusiasm for creating exceptional user experiences and your commitment to continuous improvement. By combining technical proficiency, a strong portfolio, effective networking, and excellent soft skills, you can significantly increase your chances of landing a rewarding frontend developer job.`,

  backend: `Securing a backend developer job involves demonstrating a solid understanding of server-side technologies, database management, and system architecture. Backend developers are responsible for the server-side logic, database management, and API development that power web and mobile applications. To excel in this field, you need to be proficient in programming languages like Python, Java, Node.js, or Ruby, and have a deep understanding of database systems such as MySQL, PostgreSQL, or MongoDB. A strong foundation in data structures, algorithms, and software design principles is essential. Employers often look for candidates who can design and implement scalable and efficient backend systems. Building a portfolio that showcases your backend projects is crucial. Include projects that demonstrate your ability to design RESTful APIs, manage databases, and implement server-side logic. Contribution to open-source projects or personal projects that solve real-world problems can significantly enhance your credibility. Networking is vital for landing a backend job. Attend industry meetups, join online communities, and connect with professionals on platforms like LinkedIn. Building relationships with recruiters and hiring managers can open doors to opportunities that might not be publicly advertised. Soft skills are equally important. Communication, teamwork, and problem-solving skills are highly valued in collaborative development environments. Be prepared to discuss your approach to problem-solving, your ability to work in a team, and your communication style during interviews. Continuous learning is essential in the ever-evolving world of backend development. Stay updated with the latest trends, tools, and best practices. Follow industry blogs, attend webinars, and take online courses to enhance your skills. Certifications from reputable organizations can also validate your knowledge and expertise. Tailor your resume and cover letter to each job application, highlighting the skills and experiences that align with the job requirements. Use keywords from the job description to ensure your application gets noticed by applicant tracking systems (ATS). Prepare for technical interviews by practicing coding challenges and reviewing fundamental concepts. Be ready to discuss your projects in detail, explaining your design decisions and technical implementations. A positive attitude, a willingness to learn, and a passion for backend development are crucial for success. Demonstrate your enthusiasm for creating robust and scalable systems and your commitment to continuous improvement. By combining technical proficiency, a strong portfolio, effective networking, and excellent soft skills, you can significantly increase your chances of landing a rewarding backend developer job.`,

  fullstack: `Becoming a full stack developer requires a comprehensive understanding of both frontend and backend technologies, along with the ability to bridge the gap between them. Full stack developers are responsible for building and maintaining the entire application, from the user interface to the server-side logic and database management. To excel in this field, you need to be proficient in a wide range of technologies, including HTML, CSS, JavaScript, and backend languages like Python, Java, Node.js, or Ruby. A strong understanding of database systems such as MySQL, PostgreSQL, or MongoDB, and experience with modern frameworks and libraries like React, Angular, Vue.js, and Express.js is essential. Employers often look for candidates who can demonstrate their ability to build complete web applications from scratch. Building a portfolio that showcases your full stack projects is crucial. Include projects that demonstrate your ability to design and implement both the frontend and backend of an application. Contribution to open-source projects or personal projects that solve real-world problems can significantly enhance your credibility. Networking is vital for landing a full stack job. Attend industry meetups, join online communities, and connect with professionals on platforms like LinkedIn. Building relationships with recruiters and hiring managers can open doors to opportunities that might not be publicly advertised. Soft skills are equally important. Communication, teamwork, and problem-solving skills are highly valued in collaborative development environments. Be prepared to discuss your approach to problem-solving, your ability to work in a team, and your communication style during interviews. Continuous learning is essential in the ever-evolving world of full stack development. Stay updated with the latest trends, tools, and best practices. Follow industry blogs, attend webinars, and take online courses to enhance your skills. Certifications from reputable organizations can also validate your knowledge and expertise. Tailor your resume and cover letter to each job application, highlighting the skills and experiences that align with the job requirements. Use keywords from the job description to ensure your application gets noticed by applicant tracking systems (ATS). Prepare for technical interviews by practicing coding challenges and reviewing fundamental concepts. Be ready to discuss your projects in detail, explaining your design decisions and technical implementations. A positive attitude, a willingness to learn, and a passion for full stack development are crucial for success. Demonstrate your enthusiasm for creating complete and robust applications and your commitment to continuous improvement. By combining technical proficiency, a strong portfolio, effective networking, and excellent soft skills, you can significantly increase your chances of landing a rewarding full stack developer job.`,

  uiux: `Securing a UI/UX designer job requires a strong portfolio that showcases your design skills, user-centered approach, and ability to create intuitive and engaging user experiences. UI/UX designers are responsible for designing the visual interface and user experience of digital products, ensuring they are both aesthetically pleasing and easy to use. To excel in this field, you need to be proficient in design tools like Figma, Sketch, or Adobe XD, and have a strong understanding of user research, information architecture, and interaction design. A solid understanding of design principles, typography, and color theory is essential. Employers often look for candidates who can demonstrate their ability to create user-friendly and visually appealing designs. Building a portfolio that showcases your UI/UX projects is crucial. Include projects that demonstrate your ability to conduct user research, create wireframes and prototypes, and design high-fidelity mockups. Contribution to open-source projects or personal projects that solve real-world design problems can significantly enhance your credibility. Networking is vital for landing a UI/UX job. Attend design conferences, join online communities, and connect with professionals on platforms like LinkedIn. Building relationships with recruiters and hiring managers can open doors to opportunities that might not be publicly advertised. Soft skills are equally important. Communication, teamwork, and problem-solving skills are highly valued in collaborative design environments. Be prepared to discuss your design process, your approach to user research, and your ability to work in a team during interviews. Continuous learning is essential in the ever-evolving world of UI/UX design. Stay updated with the latest design trends, tools, and best practices. Follow design blogs, attend webinars, and take online courses to enhance your skills. Certifications from reputable organizations can also validate your knowledge and expertise. Tailor your resume and cover letter to each job application, highlighting the skills and experiences that align with the job requirements. Use keywords from the job description to ensure your application gets noticed by applicant tracking systems (ATS). Prepare for design interviews by practicing design challenges and reviewing fundamental concepts. Be ready to discuss your projects in detail, explaining your design decisions and user research findings. A positive attitude, a willingness to learn, and a passion for UI/UX design are crucial for success. Demonstrate your enthusiasm for creating exceptional user experiences and your commitment to continuous improvement. By combining design proficiency, a strong portfolio, effective networking, and excellent soft skills, you can significantly increase your chances of landing a rewarding UI/UX designer job.`,

  ai: `Becoming an AI developer requires a strong foundation in computer science, mathematics, and machine learning, along with the ability to apply these concepts to build intelligent systems. AI developers are responsible for designing, developing, and deploying machine learning models and AI applications. To excel in this field, you need to be proficient in programming languages like Python, and have a strong understanding of machine learning frameworks and libraries like TensorFlow, PyTorch, and Scikit-learn. A solid understanding of data structures, algorithms, and software engineering principles is essential. Employers often look for candidates who can demonstrate their ability to build and deploy AI models in real-world applications. Building a portfolio that showcases your AI projects is crucial. Include projects that demonstrate your ability to train and evaluate machine learning models, and deploy AI applications. Contribution to open-source projects or personal projects that solve real-world AI problems can significantly enhance your credibility. Networking is vital for landing an AI developer job. Attend AI conferences, join online communities, and connect with professionals on platforms like LinkedIn. Building relationships with recruiters and hiring managers can open doors to opportunities that might not be publicly advertised. Soft skills are equally important. Communication, teamwork, and problem-solving skills are highly valued in collaborative AI development environments. Be prepared to discuss your approach to problem-solving, your understanding of machine learning concepts, and your ability to work in a team during interviews. Continuous learning is essential in the rapidly evolving field of AI. Stay updated with the latest research, tools, and best practices. Follow AI blogs, attend webinars, and take online courses to enhance your skills. Certifications from reputable organizations can also validate your knowledge and expertise. Tailor your resume and cover letter to each job application, highlighting the skills and experiences that align with the job requirements. Use keywords from the job description to ensure your application gets noticed by applicant tracking systems (ATS). Prepare for technical interviews by practicing coding challenges and reviewing machine learning concepts. Be ready to discuss your projects in detail, explaining your model design and evaluation results. A positive attitude, a willingness to learn, and a passion for AI development are crucial for success. Demonstrate your enthusiasm for creating innovative AI solutions and your commitment to continuous improvement. By combining technical proficiency, a strong portfolio, effective networking, and excellent soft skills, you can significantly increase your chances of landing a rewarding AI developer job.`,
};

const JobBoard = () => {
  return (
    <div className="min-h-screen bg-gradient-to-r from-purple-500 to-blue-600 text-white flex justify-center items-center p-4">
      <div className="max-w-3xl w-full bg-white p-6 rounded-lg shadow-lg text-gray-900">
        <h1 className="text-3xl font-bold text-center mb-6">Job Summaries</h1>
        <div className="space-y-4">
          <div className="p-4 mb-4 bg-gray-100 rounded-lg shadow">
            <h2 className="text-xl font-semibold">How to get a Frontend Job</h2>
            <p className="text-gray-700">{jobSummaries.frontend}</p>
          </div>
          <div className="p-4 mb-4 bg-gray-100 rounded-lg shadow">
            <h2 className="text-xl font-semibold">How to get a Backend Job</h2>
            <p className="text-gray-700">{jobSummaries.backend}</p>
          </div>
          <div className="p-4 mb-4 bg-gray-100 rounded-lg shadow">
            <h2 className="text-xl font-semibold">How to get a Full Stack Job</h2>
            <p className="text-gray-700">{jobSummaries.fullstack}</p>
          </div>
          <div className="p-4 mb-4 bg-gray-100 rounded-lg shadow">
            <h2 className="text-xl font-semibold">How to get a UI/UX Job</h2>
            <p className="text-gray-700">{jobSummaries.uiux}</p>
          </div>
          <div className="p-4 mb-4 bg-gray-100 rounded-lg shadow">
            <h2 className="text-xl font-semibold">How to become an AI Developer</h2>
            <p className="text-gray-700">{jobSummaries.ai}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default JobBoard;